config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :users, only: [:show, :edit, :update, :destroy]
  root to: 'pages#home'

  resources :contacts do
    resources :events, only: [:new, :create, :destroy, :edit, :update]
  end


  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/contact.rb
class Contact < ApplicationRecord
  include PgSearch::Model
  
  belongs_to :user
  has_many :events, dependent: :destroy
  has_one_attached :photo

  validates :first_name, presence: true
  validates :last_name, presence: true
  validates :first_name, uniqueness: { scope: :last_name }

  pg_search_scope :search_by_first_name_and_last_name,
    against: [ :first_name, :last_name ],
    using: {
      tsearch: { prefix: true }
    }
end

app/models/event.rb
class Event < ApplicationRecord
  # belongs_to :user
  belongs_to :contact
  belongs_to :type
  belongs_to :user
  has_many_attached :attachments

  validates :note, presence: true
  validates :type_id, presence: true
end

app/models/type.rb
class Type < ApplicationRecord
    has_many :contacts
end
  

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :contacts, dependent: :destroy
  has_many :events, dependent: :destroy
  has_one_attached :photo

  validates :email, presence: true
  validates :encrypted_password, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # [...]
  before_action :authenticate_user!
  include Pundit

  # Pundit: white-list approach.
  after_action :verify_authorized, except: :index, unless: :skip_pundit?
  after_action :verify_policy_scoped, only: :index, unless: :skip_pundit?

  # Uncomment when you *really understand* Pundit!
  # rescue_from Pundit::NotAuthorizedError, with: :user_not_authorized
  # def user_not_authorized
  #   flash[:alert] = "You are not authorized to perform this action."
  #   redirect_to(root_path)
  # end

  private

  def skip_pundit?
    devise_controller? || params[:controller] =~ /(^(rails_)?admin)|(^pages$)/
  end
end

app/controllers/contacts_controller.rb
# require 'pry-byebug'
class ContactsController < ApplicationController
  before_action :set_contact, only: %i[show update edit destroy]
  # skip_before_action :authenticate_user!, only: [:index]

  def index
    @contacts = policy_scope(current_user.contacts).order(created_at: :desc)
    if params[:query].present?
      @contacts = @contacts.search_by_first_name_and_last_name(params[:query])
    else
      @contacts
    end
  end

  def show
    authorize @contact 
    @events = @contact.events
  end
  
  def new
    authorize @contact = Contact.new
  end
  
  def create
    authorize @contact = Contact.new(contact_params)
    @contact.user = current_user
    if @contact.save
      redirect_to contact_path(@contact)
    else
      render :new
    end
  end
  
  def edit
    authorize @contact
  end
  
  def update
    authorize @contact
    if @contact.update(contact_params)
      redirect_to contact_path(@contact)
    else
      render :edit
    end
  end
  
  def destroy
    authorize @contact.destroy
    redirect_to contacts_path
  end
  
  private
  
  def set_contact
    @contact = current_user.contacts.find(params[:id])
  end

  def contact_params
    params.require(:contact).permit(:first_name, :last_name, :bio, :frequency, :photo)
  end
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_action :set_event, only: %i[show update edit destroy]
  before_action :set_contact, only: %i[new create edit update]

  def show
    authorize @event
  end

  def new
    authorize @event = Event.new
  end

  def create
    authorize @event = Event.new(event_params)
    @event.user_id = current_user.id
    @event.contact = @contact
    if @event.save
      redirect_to contact_path(@contact)
    else
      render :new
    end
  end

  def edit
    authorize @contact = @event.contact
  end

  def update
    authorize @event
    if @event.update(event_params)
      redirect_to contact_path(@event.contact_id)
    else
      render :edit
    end
  end

  def destroy
    authorize @event.destroy
    redirect_to contact_path(@event.contact_id)
  end

  private

  def set_contact
    @contact = Contact.find(params[:contact_id])
  end

  def set_event
    @event = Event.find(params[:id])
  end

  def event_params
    params.require(:event).permit(:type_id, :note, :contact_id)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: [:home]

  def home
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: %i[show update edit]
  
  def show
    authorize @user
  end
  
  def edit
    authorize @user
  end

  def update
    authorize @user
    # if user_params[:photo].nil?
      # @user.photo.purge
    if @user.update(user_params)
      redirect_to user_path(@user)
    else
      render :edit
    end
  end

  # def destroy
  #   authorize @user.destroy
  #   redirect_to root_path
  # end

  private

  def set_user
    @user = User.find(params[:id])
  end

  def user_params
      params.require(:user).permit(:photo)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/contacts/_form.html.erb
<%= simple_form_for(@contact) do |f| %>
    <%= f.error_notification %>
    <%= cl_image_tag @contact.photo.key, class: "rounded-circle", height: 150, width: 150, crop: :fill if contact.photo.attached? %>
    <%= f.input :first_name %>
    <%= f.input :last_name %>
    <%= f.input :bio %>
    <%= f.input :frequency, collection: [['1', 'Daily'], ['7', 'Weekly'], ['30', 'Monthly'], ['365', 'Yearly']], label_method: :second, value_method: :first %>
    <%= f.input :photo %>
    <%= f.button :submit, class: "btn-primary" %>
    <%= link_to "Cancel", :back, class: "btn btn-outline-secondary" %>
<% end %>

app/views/contacts/edit.html.erb
<div class="container">
  <div class="row justify-content-md-center mt-3">
    <div class="col-md-9">
      <nav aria-label="breadcrumb">
        <ol class="breadcrumb">
          <li class="breadcrumb-item"><%= link_to contacts_path, class: "text-reset" do %>Contacts<% end %></li>
          <li class="breadcrumb-item"><%= link_to contact_path(@contact), class: "text-reset" do %>Contact<% end %></li>
          <li class="breadcrumb-item active" aria-current="page">Edit</li>
        </ol>
      </nav>
      <div class="container bg-white p-3">
        <%= render 'form', contact: @contact %>
      </div>
    </div>
  </div>
</div>

app/views/contacts/index.html.erb
<div class="container">
  <div class="row justify-content-md-center mt-3">
    <div class="col-md-9">
      <nav aria-label="breadcrumb">
        <ol class="breadcrumb">
          <li class="breadcrumb-item active"><%= link_to contacts_path, class: "text-reset" do %>Contacts<% end %></li>
        </ol>
      </nav>
      
      <div class="list-group my-3">
        <%= form_tag contacts_path, method: :get do %>
          <%= text_field_tag :query,
            params[:query],
            class: "form-control",
            placeholder: "Find a contact"
          %>      
        <% end %>
        <% @contacts.each do |contact| %>
          <%= link_to contact_path(contact), class: "list-group-item list-group-item-action" do %>
              <% if contact.photo.attached? %>
                <%= cl_image_tag contact.photo.key, class: "rounded-circle mr-1" , height: 50, width: 50, crop: :fill %>
               <% else %>
                <%= image_tag "user_icon.png", class: "rounded-circle mr-1" , height: 50, width: 50, crop: :fill %>
              <% end %>
            <%= contact.first_name %> <%= contact.last_name %>
          <% end %>
        <% end %>
      </div>
      <%= link_to "Add new contact", new_contact_path, class: "btn btn-primary btn-lg" %>
      </p>
    </div>
  </div>
</div>

app/views/contacts/new.html.erb
<div class="container">
  <div class="row justify-content-md-center mt-3">
    <div class="col-md-9">
        <nav aria-label="breadcrumb">
        <ol class="breadcrumb">
          <li class="breadcrumb-item"><%= link_to contacts_path, class: "text-reset" do %>Contacts<% end %></li>
          <li class="breadcrumb-item active" aria-current="page">New contact</li>
        </ol>
      </nav>
      <div class="container bg-white p-3">
        <%= render 'form', contact: @contact %>
      </div>
    </div>
  </div>
</div>

app/views/contacts/show.html.erb
<div class="container">
  <div class="row justify-content-md-center mt-3">
    <div class="col-md-9">
      <nav aria-label="breadcrumb">
        <ol class="breadcrumb">
          <li class="breadcrumb-item"><%= link_to contacts_path, class: "text-reset" do %>Contacts<% end %></li>
          <li class="breadcrumb-item active" aria-current="page">Events</li>
        </ol>
      </nav>
      <div class="card w-100">
        <div class="card-body">
          <div class="d-flex justify-content-between">
            <h5 class="card-title">
              <% if @contact.photo.attached? %>
                  <%= cl_image_tag @contact.photo.key, class: "rounded-circle mr-1" , height: 50, width: 50, crop: :fill %>
                <% else %>
                  <%= image_tag "user_icon.png", class: "rounded-circle mr-1" , height: 50, width: 50, crop: :fill %>
                <% end %>
              <%= @contact.first_name %> <%= @contact.last_name %></h5>
            <div class="dropdown">
                <a class="btn btn-secondary btn-sm dropdown-toggle" href="#" role="button" id="dropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                  Actions
                </a>
                <div class="dropdown-menu" aria-labelledby="dropdownMenuLink">
                  <%= link_to "Add event", new_contact_event_path(@contact), class: "dropdown-item" %>
                  <%= link_to "Edit contact", edit_contact_path(@contact), class: "dropdown-item"%>
                  <%= link_to 'Delete contact', contact_path(@contact), method: :delete, data: { confirm: 'Are you sure?' }, class: "dropdown-item" %>
                </div>
              </div>
          </div>
            <p class="card-text"><%= @contact.bio %></p>
        </div>
      </div>

      <% @events.each do |event| %>
        <div class="card my-2">
          <div class="card-header">
            <div class="d-flex justify-content-between">
              <span><i class="fas <%= event.type.icon %> mr-1"></i><%= event.type.name %></span>
              <div class="dropdown">
                <a class="btn btn-secondary btn-sm dropdown-toggle" href="#" role="button" id="dropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                  Actions
                </a>
                <div class="dropdown-menu" aria-labelledby="dropdownMenuLink">
                  <%= link_to "Edit", edit_contact_event_path(event.contact_id, event.id), class: "dropdown-item" %> 
                  <%= link_to "Delete", contact_event_path(event.contact_id, event.id), method: :delete, data: { confirm: 'Are you sure?' }, class: "dropdown-item" %>
                </div>
              </div>
            </div>
          </div>
          <div class="card-body">
            <p class="card-text"><%= event.note %></p>
            <small><%= event.created_at.strftime('Created on %m/%d/%y') %></small>
          </div>
        </div>
      <% end %>
    </div>
  </div>
</div>



 

app/views/contacts/update.html.erb
<h1>Contacts#update</h1>
<p>Find me in app/views/contacts/update.html.erb</p>

app/views/events/_form.html.erb
<%= simple_form_for [@contact, @event] do |f| %>
    <%= f.error_notification %>
    <%= f.input :note %>
    <%= f.input :type_id, collection: Type.all.order(id: :asc), selected: 3 %>
    <%= f.button :submit, class: "btn-primary" %>
    <%= link_to "Cancel", :back, class: "btn btn-outline-secondary" %>
<% end %>

app/views/events/edit.html.erb
<div class="container">
  <div class="row justify-content-md-center mt-3">
    <div class="col-md-9">
      <nav aria-label="breadcrumb">
        <ol class="breadcrumb">
          <li class="breadcrumb-item"><%= link_to contacts_path, class: "text-reset" do %>Contacts<% end %></li>
          <li class="breadcrumb-item"><%= link_to contact_path(@contact), class: "text-reset" do %>Contact<% end %></li>
          <li class="breadcrumb-item active" aria-current="page">Edit event</li>
        </ol>
      </nav>
      <div class="container bg-white p-3">
        <%= render 'form', contact: @contact, event: @event %>
      </div>
    </div>
  </div>
</div>

app/views/events/new.html.erb
<div class="container">
  <div class="row justify-content-md-center mt-3">
    <div class="col-md-9">
      <nav aria-label="breadcrumb">
        <ol class="breadcrumb">
          <li class="breadcrumb-item"><%= link_to contacts_path, class: "text-reset" do %>Contacts<% end %></li>
          <li class="breadcrumb-item"><%= link_to contact_path(@contact), class: "text-reset" do %>Contact<% end %></li>
          <li class="breadcrumb-item active" aria-current="page">New event</li>
        </ol>
      </nav>
      <div class="container bg-white p-3">
        <%= render 'form', contact: @contact, event: @event %>
      </div>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="EN">
  <head>
    <!-- Global site tag (gtag.js) - Google Analytics -->
    <script async src="https://www.googletagmanager.com/gtag/js?id=UA-92238361-3"></script>
    <script>
      window.dataLayer = window.dataLayer || [];
      function gtag(){dataLayer.push(arguments);}
      gtag('js', new Date());

      gtag('config', 'UA-92238361-3');
    </script>

    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>2network</title>
    <%= csrf_meta_tags %>
    <%= action_cable_meta_tag %>
    <%= stylesheet_link_tag 'application', media: 'all' %>
    <%#= stylesheet_pack_tag 'application', media: 'all' %> <!-- Uncomment if you import CSS in app/javascript/packs/application.js -->
  </head>
  <body>
    <%= render 'shared/navbar' %>
    <%= render 'shared/flashes' %>
    <%= yield %>
    <%= javascript_include_tag 'application' %>
    <%= javascript_pack_tag 'application' %>
  </body>
</html>

app/views/pages/home.html.erb
<div class="container">
  <div class="row justify-content-md-center mt-3">
    <div class="col-md-9">
      <h1>2network app</h1>
      <p>One app to manage your social network. Take notes about your important moments</p>
      <%= link_to "Start", contacts_path, class: "btn btn-primary" %>
    </div>
  </div>
</div>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <%= notice %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <%= alert %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-dark navbar-lewagon">
  <%= link_to root_path, class: "navbar-brand" do %>
    <%= image_tag "logo.png" %>
  <% end %>

  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>


  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <% if user_signed_in? %>
        <li class="nav-item active">
          <%= link_to "Home", root_path, class: "nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to "Contacts", contacts_path, class: "nav-link" %>
        </li>
        <li class="nav-item dropdown">
          <% if current_user.photo.attached? %>
            <%= cl_image_tag current_user.photo.key, class: "avatar dropdown-toggle", id: "navbarDropdown", data: { toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false, height: 40 %>
          <% else %>
            <%= image_tag "user_icon.png", class: "avatar dropdown-toggle", id: "navbarDropdown", data: { toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
          <% end %>
          <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
            <%= link_to 'My account', user_path(current_user), class: "dropdown-item" %>
            <%= link_to "Log out", destroy_user_session_path, method: :delete, class: "dropdown-item" %>
          </div>
        </li>
      <% else %>
        <li class="nav-item">
          <%= link_to "Login", new_user_session_path, class: "nav-link" %>
        </li>
      <% end %>
    </ul>
  </div>
</div>

app/views/users/_form.html.erb
<%= simple_form_for(@user) do |f| %>
    <%= f.error_notification %>
    <%= f.input :photo %>
    <%= f.button :submit, class: "btn-primary" %>
    
    <%= f.button :button, "Cancel", type: "reset", class: "btn-outline-secondary" %>
<% end %>

app/views/users/edit.html.erb
<div class="container">
  <div class="row justify-content-md-center mt-3">
    <div class="col-md-9">
      <h2>Account > Edit</h2>
      <% if current_user.photo.attached? %>
        <%= cl_image_tag current_user.photo.key, class: "rounded-circle mr-1" , height: 50, width: 50, crop: :fill %>
      <% else %>
        <%= image_tag "user_icon.png", class: "rounded-circle mr-1" , height: 50, width: 50, crop: :fill %>
      <% end %>
      <%= render 'form', user: @user %>      
    </div>
  </div>
</div>

app/views/users/show.html.erb
<div class="container">
  <div class="row justify-content-md-center mt-3">
    <div class="col-md-9">
      <h2>Account</h2>
      <% if @user.photo.attached? %>
        <%= cl_image_tag @user.photo.key, class: "rounded-circle mr-1" , height: 50, width: 50, crop: :fill %>
      <% else %>
        <%= image_tag "user_icon.png", class: "rounded-circle mr-1" , height: 50, width: 50, crop: :fill %>
      <% end %>
      <%= @user.email %>
      <br />
      <%= link_to  "Change avatar", edit_user_path(@user.id), class: "btn btn-secondary" %>
      <%= link_to 'Change password or email', edit_user_registration_path(@user), class: "btn btn-secondary" %>
    </div>
  </div>
</div>